import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import '../styles/global.css'
import Header from "@/pages/layouts/header";
import Footer from "@/pages/layouts/footer";
import Global from "@/components/global";
import { Providers } from "@/store/providers";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} antialiased text-white`}
      >
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />

          {/* global somethings like popup */}
          <Global />
        </Providers>
      </body>
    </html>
  );
}
